name: Create pull request
on:
  push:
    branches:
      - main
jobs:
  createPullRequest:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Create tmp branch
        run: git fetch orign refs/for/main:tmp
      - uses: actions/checkout@v2
        with:
          ref: tmp