name: Create pull request
on:
  push:
    branches:
      - main
jobs:
  createPullRequest:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
      - name: Create tmp branch
        run: git fetch orign ${{github.ref}}:tmp
      - uses: actions/checkout@v2
        with:
          ref: tmp